# Generated by Django 4.2 on 2023-04-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_coordinates_city_datetime_city_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='preassure',
            new_name='pressure',
        ),
    ]
