# Generated by Django 4.2 on 2023-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_preassure_city_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='datetime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='wind_deg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='wind_gust',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='wind_speed',
            field=models.FloatField(),
        ),
    ]
