# Generated by Django 4.2 on 2023-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_city_datetime_alter_city_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
